name: Execute Workflow
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: workflow execute
    steps:
      - name: execute
        id: execute
        with:
          wait: true
          server: playground.direktiv.io
          workflow: github/install-app
          token: ${{ secrets.DIREKTIV_TOKEN }}
        uses: vorteil/direktiv-actions-ghexec@v1
